meta_product_name: "Globeup"
meta_title: "Globeup - Find your tribe abroad!"
meta_description: "Women connecting with women across the world"
meta_image: "cover-photo.jpg" # should exist in `app/assets/images/`
